# Import Liberaries 

In [44]:
import json 
from sklearn.preprocessing import LabelEncoder
import numpy as np 
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

Read Data

In [45]:
with open('data1.json') as file:
    data=json.load(file)

In [46]:

data

{'data': [{'label': 'greeting',
   'patterns': ['Hi', 'Hey', 'Is anyone there?', 'Hello', 'Hay'],
   'responses': ['Hello', 'Hi', 'Hi there', 'Hey']},
  {'label': 'Visa and Entry Requirements',
   'patterns': ['What are the visa requirements for visiting Egypt?',
    'How do I obtain a tourist visa for Egypt?',
    'Are there any entry restrictions or requirements due to COVID-19?'],
   'responses': ['On Arrival:$27 (up to 30 days) or $62 (up to 90 days),By Mail:$62 for single entry,In Person:$70 for single entry,E-Visa:$25 for a single-entry',
    'As of the latest information available, there are no mandatory COVID-19 vaccination or testing requirements for entering Egypt. However, travelers should still monitor official sources for potential updates, especially since global pandemic policies evolve rapidly. It is essential to adhere to general hygiene measures and follow any advice provided by local authorities']},
  {'label': 'Safety and Security',
   'patterns': ['Is Egypt a safe 

Create training example , label and response 

In [47]:
training_example=[]
training_labels=[]
response=[]

for example in data['data']:
    for pattern in example['patterns']:
        training_example.append(pattern)
        training_labels.append(example['label'])
    response.append(example['responses'])


In [48]:
print("training example ")
print(training_example)

training example 
['Hi', 'Hey', 'Is anyone there?', 'Hello', 'Hay', 'What are the visa requirements for visiting Egypt?', 'How do I obtain a tourist visa for Egypt?', 'Are there any entry restrictions or requirements due to COVID-19?', 'Is Egypt a safe destination for tourists?', 'Are there any specific safety precautions I should be aware of?', 'What areas should I avoid as a tourist?', 'What are the transportation options available within Egypt?', 'How do I get from the airport to my accommodation?', 'Are there any recommended modes of transportation for traveling between cities or attractions?', 'What are some recommended hotels or accommodations in cairo?', 'Are there any budget-friendly options available?', 'How can I book accommodation in advance?', 'What are the must-visit attractions in Egypt?', 'Can you recommend any guided tours or experiences?', 'Are there any lesser-known attractions or hidden gems worth exploring?', 'What are some cultural norms and etiquette I should be a

In [49]:
print("training label ")
print(training_labels)

training label 
['greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'Visa and Entry Requirements', 'Visa and Entry Requirements', 'Visa and Entry Requirements', 'Safety and Security', 'Safety and Security', 'Safety and Security', 'Transportation', 'Transportation', 'Transportation', 'Accommodation', 'Accommodation', 'Accommodation', 'Tourist Attractions', 'Tourist Attractions', 'Tourist Attractions', 'Cultural Etiquette', 'Cultural Etiquette', 'Cultural Etiquette', 'Food and Dining', 'Food and Dining', 'Food and Dining', 'Language and Communication', 'Language and Communication', 'Language and Communication', 'Weather and Climate', 'Weather and Climate', 'Weather and Climate', 'Currency and Money Matters', 'Currency and Money Matters', 'Currency and Money Matters', 'thanks', 'thanks', 'thanks', 'thanks', 'goodbye', 'goodbye', 'goodbye']


In [50]:
print('Response')
print(response)

Response
[['Hello', 'Hi', 'Hi there', 'Hey'], ['On Arrival:$27 (up to 30 days) or $62 (up to 90 days),By Mail:$62 for single entry,In Person:$70 for single entry,E-Visa:$25 for a single-entry', 'As of the latest information available, there are no mandatory COVID-19 vaccination or testing requirements for entering Egypt. However, travelers should still monitor official sources for potential updates, especially since global pandemic policies evolve rapidly. It is essential to adhere to general hygiene measures and follow any advice provided by local authorities'], ['The Egyptian government has taken steps to improve security in recent years, and the overall threat level has decreased.', 'maintaining situational awareness and following local recommendations can greatly reduce the chances of experiencing issues while traveling in Egypt.', 'Some tips for staying safe in Egypt include:Monitor local news sources for potential dangers and adjust plans accordingly.Avoid crowded places, politic

In [51]:
len(training_labels)

42

In [52]:
len(set(training_labels))

13

Preprocessing

In [53]:
training_example

['Hi',
 'Hey',
 'Is anyone there?',
 'Hello',
 'Hay',
 'What are the visa requirements for visiting Egypt?',
 'How do I obtain a tourist visa for Egypt?',
 'Are there any entry restrictions or requirements due to COVID-19?',
 'Is Egypt a safe destination for tourists?',
 'Are there any specific safety precautions I should be aware of?',
 'What areas should I avoid as a tourist?',
 'What are the transportation options available within Egypt?',
 'How do I get from the airport to my accommodation?',
 'Are there any recommended modes of transportation for traveling between cities or attractions?',
 'What are some recommended hotels or accommodations in cairo?',
 'Are there any budget-friendly options available?',
 'How can I book accommodation in advance?',
 'What are the must-visit attractions in Egypt?',
 'Can you recommend any guided tours or experiences?',
 'Are there any lesser-known attractions or hidden gems worth exploring?',
 'What are some cultural norms and etiquette I should be

In [54]:
def clean_text(sentences):
    result=[]
    for sentence in sentences:
        #sentence=re.sub(r'\W',' ',sentence)# pattern  # text 
        sentence=sentence.lower()
        result.append(sentence)
        
    return result

In [55]:
training_example=clean_text(training_example)

convert label values

In [56]:
le=LabelEncoder()
le.fit(training_labels)
training_labels=le.fit_transform(training_labels)

In [57]:
training_labels

array([11, 11, 11, 11, 11,  8,  8,  8,  5,  5,  5,  7,  7,  7,  0,  0,  0,
        6,  6,  6,  1,  1,  1,  3,  3,  3,  4,  4,  4,  9,  9,  9,  2,  2,
        2, 12, 12, 12, 12, 10, 10, 10], dtype=int64)

In [58]:
training_labels=to_categorical(training_labels)
training_labels

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 

Convert words to vectors

In [59]:
from tensorflow.keras.preprocessing.text import one_hot 
sequnces=[one_hot(example,50,filters='') for example in training_example]
print(sequnces)

[[16], [7], [5, 5, 21], [26], [24], [14, 3, 26, 11, 38, 26, 36, 37], [38, 42, 36, 12, 38, 25, 11, 26, 37], [3, 34, 39, 19, 42, 48, 38, 8, 6, 36], [5, 7, 38, 42, 6, 26, 44], [3, 34, 39, 18, 46, 3, 36, 4, 6, 11, 15], [14, 34, 4, 36, 2, 3, 38, 12], [14, 3, 26, 21, 4, 43, 30, 37], [38, 42, 36, 26, 35, 26, 41, 6, 33, 12], [3, 34, 39, 33, 17, 31, 21, 26, 48, 5, 20, 48, 46], [14, 3, 16, 33, 13, 48, 8, 25, 1], [3, 34, 39, 9, 4, 47], [38, 39, 36, 19, 22, 25, 3], [14, 3, 26, 2, 16, 25, 37], [39, 1, 36, 39, 45, 17, 48, 24], [3, 34, 39, 21, 16, 48, 20, 41, 9, 22], [14, 3, 16, 47, 49, 31, 46, 36, 4, 6, 11, 31, 25, 37], [5, 34, 38, 18, 42, 34, 36, 4, 33, 19, 36, 43, 15], [3, 34, 39, 44, 48, 30, 36, 4, 44, 34, 33, 1], [14, 3, 16, 33, 29, 40, 36, 4, 38], [39, 1, 36, 39, 28, 48, 14, 32, 27, 22, 26, 47, 14], [3, 34, 39, 7, 42, 48, 36, 36, 4, 6, 11, 15], [14, 19, 3, 42, 29, 25, 37], [33, 36, 6, 44, 6, 20, 25, 23, 25, 45, 25, 15], [3, 34, 39, 17, 41, 48, 32, 36, 4, 41, 25, 9], [14, 5, 26, 32, 25, 37], [3,

In [60]:
toknizer=Tokenizer(num_words=100)
toknizer.fit_on_texts(training_example)
sequnces=toknizer.texts_to_sequences(training_example)
print(sequnces)

[[44], [45], [14, 46, 3], [47], [48], [6, 1, 10, 25, 26, 11, 27, 9], [19, 28, 2, 49, 16, 20, 25, 11, 9], [1, 3, 4, 50, 29, 7, 26, 51, 21, 52, 53], [14, 9, 16, 54, 55, 11, 56], [1, 3, 4, 30, 57, 58, 2, 5, 12, 15, 13], [6, 31, 5, 2, 59, 60, 16, 20], [6, 1, 10, 32, 33, 34, 61, 9], [19, 28, 2, 62, 63, 10, 64, 21, 22, 35], [1, 3, 4, 36, 65, 13, 32, 11, 66, 67, 68, 7, 23], [6, 1, 24, 36, 69, 7, 70, 8, 71], [1, 3, 4, 72, 73, 33, 34], [19, 17, 2, 74, 35, 8, 75], [6, 1, 10, 76, 37, 23, 8, 9], [17, 18, 38, 4, 77, 78, 7, 79], [1, 3, 4, 80, 39, 23, 7, 81, 82, 83, 84], [6, 1, 24, 85, 86, 40, 87, 2, 5, 12, 15, 13, 8, 9], [14, 3, 16, 30, 88, 89, 2, 5, 90, 91, 27, 92, 93], [1, 3, 4, 41, 7, 94, 2, 5, 95, 96, 22, 37], [6, 1, 24, 97, 98, 99, 2, 5], [17, 18, 38, 4, 7, 39, 11], [1, 3, 4, 29, 7, 42, 2, 5, 12, 15, 13], [6, 1, 8, 9], [2, 12, 21, 8, 8, 20, 31], [1, 3, 4, 7, 2, 5, 8], [6, 14, 10, 8, 9], [1, 3, 4, 42, 2, 5, 12, 15, 13], [6, 5, 2, 11, 22, 10], [6, 14, 10, 8, 9, 40, 17, 2], [1, 7, 5, 2], [1, 3, 4,

In [61]:
padded_sequence=pad_sequences(sequnces,truncating='post',maxlen=20)
print(padded_sequence)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 44]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 45]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14 46  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 47]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 48]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  6  1 10 25 26 11 27  9]
 [ 0  0  0  0  0  0  0  0  0  0  0 19 28  2 49 16 20 25 11  9]
 [ 0  0  0  0  0  0  0  0  0  1  3  4 50 29  7 26 51 21 52 53]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 14  9 16 54 55 11 56]
 [ 0  0  0  0  0  0  0  0  0  1  3  4 30 57 58  2  5 12 15 13]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  6 31  5  2 59 60 16 20]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  6  1 10 32 33 34 61  9]
 [ 0  0  0  0  0  0  0  0  0  0 19 28  2 62 63 10 64 21 22 35]
 [ 0  0  0  0  0  0  0  1  3  4 36 65 13 32 11 66 67 68  7 23]
 [ 0  0  0  0  0  0  0  0  0  0  0  6  1 24 36 69  7 70  8 71]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  3  4 72 73

In [62]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense ,LSTM,Embedding ,GlobalAveragePooling1D

model=Sequential()
model.add(Embedding(100,10,input_length=20))
model.add(GlobalAveragePooling1D())
model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(13,activation='softmax'))


model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 10)            1000      
                                                                 
 global_average_pooling1d_1  (None, 10)                0         
  (GlobalAveragePooling1D)                                       
                                                                 
 dense_3 (Dense)             (None, 128)               1408      
                                                                 
 dense_4 (Dense)             (None, 64)                8256      
                                                                 
 dense_5 (Dense)             (None, 13)                845       
                                                                 
Total params: 11509 (44.96 KB)
Trainable params: 11509 (44.96 KB)
Non-trainable params: 0 (0.00 Byte)
__________________

In [65]:
history=model.fit(np.array(padded_sequence),training_labels,epochs=400)


Epoch 1/400
2/2 [==============================] - 0s 6ms/step - loss: 0.0872 - accuracy: 0.9524
Epoch 2/400
2/2 [==============================] - 0s 5ms/step - loss: 0.0863 - accuracy: 0.9524
Epoch 3/400
2/2 [==============================] - 0s 6ms/step - loss: 0.0865 - accuracy: 0.9524
Epoch 4/400
2/2 [==============================] - 0s 0s/step - loss: 0.0859 - accuracy: 0.9524
Epoch 5/400
2/2 [==============================] - 0s 672us/step - loss: 0.0866 - accuracy: 0.9524
Epoch 6/400
2/2 [==============================] - 0s 17ms/step - loss: 0.0844 - accuracy: 0.9524
Epoch 7/400
2/2 [==============================] - 0s 0s/step - loss: 0.0843 - accuracy: 0.9524
Epoch 8/400
2/2 [==============================] - 0s 8ms/step - loss: 0.0845 - accuracy: 0.9524
Epoch 9/400
2/2 [==============================] - 0s 5ms/step - loss: 0.0842 - accuracy: 0.9524
Epoch 10/400
2/2 [==============================] - 0s 0s/step - loss: 0.0852 - accuracy: 0.9524
Epoch 11/400
2/2 [===========

Save Model

In [66]:
inp='hello'
sent=pad_sequences(toknizer.texts_to_sequences([inp]),maxlen=20)
print(sent)
result=np.argmax(model.predict(np.array(sent))) # 0-7 
print(result)
f_res=le.inverse_transform(np.array(result).reshape(1))
print(f_res)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 47]]
1/1 [==============================] - 0s 81ms/step
11
['greeting']


## Save Model


In [24]:
tokenizer_json = toknizer.to_json()
with open('tokenizer.json', 'w') as json_file:
    json_file.write(tokenizer_json)

# Save label encoder to JSON
label_encoder_json = json.dumps(le.classes_.tolist())
with open('label_encoder.json', 'w') as json_file:
    json_file.write(label_encoder_json)

In [67]:
import pickle as pk 
#save tokinizer
pk.dump(toknizer,open("toknizer.pkl","wb"))

In [68]:
#save encoder
pk.dump(le,open("label_encoder.pkl","wb"))

In [69]:
model.save('model.h5') # save model 
from tensorflow.keras.models import load_model
model=load_model('model.h5') # load model 

c:\Users\Campos\.conda\envs\tf\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [70]:
from tensorflow.keras.models import load_model
model=load_model('model.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open('model.tflite', 'wb') as f:
    f.write(tflite_model)

INFO:tensorflow:Assets written to: C:\Users\Campos\AppData\Local\Temp\tmp2h96uoc0\assets


INFO:tensorflow:Assets written to: C:\Users\Campos\AppData\Local\Temp\tmp2h96uoc0\assets


Interface

In [30]:
def user_chat():
    while True :
        print("User : ",end="") 
        inp=input()

        if inp.lower()=='quit':
            break
        
        sent=pad_sequences(toknizer.texts_to_sequences([inp]),maxlen=20) #[] len=20

        result=np.argmax(model.predict(np.array(sent),verbose=0)) # 0-7 
        # 2 ,3 , 4
        f_res=le.inverse_transform(np.array(result).reshape(1))


        for label in data['data']:

            if label['label']==f_res:

                print('ChatBot : ',np.random.choice(label['responses']))



In [34]:
print("Start Conversation with Chatbot")
user_chat()

Start Conversation with Chatbot
User : ChatBot :  Hi there
User : ChatBot :  Hello
User : ChatBot :  Mainly Arabic and Egyptian Arabic, with some English and French speakers.
User : ChatBot :  Have a nice day
User : ChatBot :  Have a nice day
User : ChatBot :  Bye! Come back again
User : ChatBot :  Have a nice day
User : ChatBot :  See you later
User : 

In [73]:
import json 
import tensorflow
import sklearn
json.__version__ , tf.__version__ ,sklearn.__version__

('2.0.9', '2.15.0', '1.4.0')